### ISSUE TITLE
Possibly incompatible with C2ME

### ISSUE THREAD

**Issue by Sunconure11** [orlouge/structure-palettes#1]
https://github.com/RelativityMC/C2ME-fabric/issues/146

**Comment by Sunconure11** [comment]
@orlouge Sorry about the ping

**Comment by orlouge** [comment]
Both mods attempt to change the same parts of the code, and Structure Palettes does it in a way that shouldn't cause incompatibilities with other mods in most cases, unless they overwrite the whole method altogether like C2ME does.
