### ISSUE TITLE
[SUGGESTION] Command to find variants of structures

### ISSUE THREAD

**Issue by Sunconure11** [orlouge/structure-palettes#2]
I’m trying to see if a palette I made worked, but I have no way of telling without randomly teleporting in hopes of maybe finding a village with my palette. Would it be possible to add some kind of command or something to find villages using said palettes?

**Comment by orlouge** [comment]
Too complex and slow to be worth it, it would have to /locate many times until it finds a structure with a matching palette, and currently palettes don't have anything that identifies them so I'm not sure how such a command would work.
Just set the weight of the palette you want to debug to a high value.
