### ISSUE TITLE
Cannot Launch Game

### ISSUE THREAD

**Issue by ardissaps** [orlouge/structure-palettes#4]
https://paste.atlauncher.com/view/b3bfb4a8-a266-49da-bf2b-291d8a33ef64

**Comment by orlouge** [comment]
This mod is for Fabric, not Quilt.

**Comment by ardissaps** [comment]
Yeah I have bot fabric and quilt, both run well but not compatible with [C2ME](https://modrinth.com/mod/c2me-fabric). So it is not quilt problem but C2ME, so you can check out C2ME. I play 1.18.2 Fabric, and 1.19 Quilt.
